# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: My-macbook

steps:
- script: |
    python3 -m venv venv
    source venv/bin/activate
    pip install -r app/requirements.txt
    pip install pytest
  displayName: 'Install dependencies'

- script: |
    source venv/bin/activate
    pytest
  displayName: 'Run tests'
